version: '3'
services:
  etl:
    build: .
    volumes:
      - .:/app
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

## user=user, password=password as default